import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Service — Celune',
  description: 'Terms and conditions for using Celune.',
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-24 text-neutral-300">
      <Link href="/" className="mb-8 inline-block text-sm text-neutral-500 hover:text-white">
        &larr; Back to Celune
      </Link>

      <h1 className="mb-8 text-3xl font-bold text-white">Terms of Service</h1>
      <p className="mb-6 text-sm text-neutral-500">Last updated: March 8, 2026</p>

      <div className="space-y-8 text-sm leading-relaxed">
        <section>
          <h2 className="mb-3 text-lg font-semibold text-white">1. Acceptance of Terms</h2>
          <p>
            By accessing or using Celune, you agree to be bound by these Terms of Service.
            If you do not agree, do not use the service.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-white">2. Description of Service</h2>
          <p>
            Celune provides an agentic engineering platform that deploys autonomous AI agents to write code,
            manage tasks, and run development pipelines. The service includes a web dashboard, API access,
            and integrations with third-party tools.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-white">3. Account Responsibilities</h2>
          <p>
            You are responsible for maintaining the security of your account credentials.
            You must be at least 18 years old to use Celune. You are responsible for all activity
            that occurs under your account, including actions taken by AI agents you configure.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-white">4. Acceptable Use</h2>
          <p>You agree not to use Celune to:</p>
          <ul className="mt-2 list-inside list-disc space-y-1 text-neutral-400">
            <li>Violate any laws or regulations</li>
            <li>Generate malicious code, malware, or exploits</li>
            <li>Impersonate others or misrepresent your identity</li>
            <li>Interfere with or disrupt the service</li>
            <li>Attempt to access other users&apos; data without authorization</li>
          </ul>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-white">5. Billing & Subscriptions</h2>
          <p>
            Paid plans are billed monthly. You can cancel at any time. Cancellation takes effect
            at the end of the current billing period. Refunds are not provided for partial months.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-white">6. Intellectual Property</h2>
          <p>
            You retain ownership of all code and content you create using Celune. Celune retains
            ownership of the platform, including its AI models, agents, and infrastructure.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-white">7. Limitation of Liability</h2>
          <p>
            Celune is provided &quot;as is&quot; without warranties of any kind. We are not liable for
            any damages arising from your use of the service, including but not limited to code
            generated by AI agents. You are responsible for reviewing and testing all agent-generated output.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-white">8. Termination</h2>
          <p>
            We may suspend or terminate your account if you violate these terms. Upon termination,
            your right to use the service ceases immediately. You may export your data before termination.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-white">9. Changes to Terms</h2>
          <p>
            We may modify these terms at any time. Continued use of the service after changes
            constitutes acceptance. We will notify you of material changes via email.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-white">10. Contact</h2>
          <p>
            Questions about these terms? Contact us at{' '}
            <a href="mailto:hello@celune.ai" className="text-white underline">hello@celune.ai</a>.
          </p>
        </section>
      </div>
    </div>
  );
}
